import re
import urllib.request
from pathlib import Path

SOURCE = "https://raw.githubusercontent.com/doms9/iptv/refs/heads/default/M3U8/events.m3u8"

CHANNEL_FILE = "channel"

BEGIN_MARKER = "# --- BEGIN AUTOGENERATED doms9/events.m3u8 (SOCCER ONLY) ---"
END_MARKER = "# --- END AUTOGENERATED doms9/events.m3u8 (SOCCER ONLY) ---"

KEYWORDS = [
    "football",
    "soccer",
    "fifa",
    "world cup",
    "copa del mundo",
    "futbol"
]

raw = urllib.request.urlopen(SOURCE, timeout=30).read().decode("utf-8", "ignore")

lines = raw.splitlines()

blocks = []
i = 0

while i < len(lines):
    if lines[i].startswith("#EXTINF"):
        block = [lines[i]]
        i += 1

        while i < len(lines) and not lines[i].startswith("#EXTINF"):
            block.append(lines[i])
            i += 1

        text = " ".join(block).lower()

        if any(k in text for k in KEYWORDS):
            blocks.append("\n".join(block))
    else:
        i += 1

generated = (
    BEGIN_MARKER
    + "\n"
    + "\n\n".join(blocks)
    + "\n"
    + END_MARKER
)

channel = Path(CHANNEL_FILE)
content = channel.read_text(encoding="utf-8")

if BEGIN_MARKER in content and END_MARKER in content:
    content = re.sub(
        re.escape(BEGIN_MARKER)
        + r".*?"
        + re.escape(END_MARKER),
        generated,
        content,
        flags=re.S,
    )
else:
    content += "\n\n" + generated

channel.write_text(content, encoding="utf-8")

print(f"Updated {len(blocks)} soccer events")
