import re
import urllib.request
import urllib.error
import json
from pathlib import Path
import hashlib

SOURCE = "https://raw.githubusercontent.com/doms9/iptv/refs/heads/default/M3U8/events.m3u8"
HASH_FILE = ".last_events_hash"
STATUS_FILE = "channel_status.json"
MAX_FAILURES = 4

CHANNEL_FILE = "channel"

BEGIN_MARKER = "# --- BEGIN AUTOGENERATED doms9/events.m3u8 (SOCCER ONLY) ---"
END_MARKER = "# --- END AUTOGENERATED doms9/events.m3u8 (SOCCER ONLY) ---"

BLOCKED = [
    "cricket",
    "baseball",
    "mlb",
    "nba",
    "wnba",
    "basketball",
    "nfl",
    "american football",
    "nhl",
    "hockey",
    "ufc",
    "mma",
    "boxing",
    "wwe",
    "aew",
    "rugby",
    "formula 1",
    "f1",
    "motogp",
    "nascar",
    "tennis",
    "atp",
    "wta",
    "golf",
    "pga",
    "volleyball",
    "handball",
    "badminton",
    "snooker",
    "darts"
]

raw = urllib.request.urlopen(SOURCE, timeout=30).read().decode("utf-8", "ignore")
current_hash = hashlib.sha256(raw.encode()).hexdigest()

hash_path = Path(HASH_FILE)

old_hash = ""
if hash_path.exists():
    old_hash = hash_path.read_text().strip()

if current_hash == old_hash:
    print("No changes in doms9 source")
    raise SystemExit(0)

hash_path.write_text(current_hash)

lines = raw.splitlines()
def is_alive(url):
    try:
        req = urllib.request.Request(
            url,
            headers={"User-Agent": "Mozilla/5.0"}
        )

        with urllib.request.urlopen(req, timeout=15) as r:
            return r.status in (200, 206)

    except Exception:
        return False

blocks = []
i = 0

while i < len(lines):
    if lines[i].startswith("#EXTINF"):
        block = [lines[i]]
        i += 1

        while i < len(lines) and not lines[i].startswith("#EXTINF"):
            block.append(lines[i])
            i += 1

        text = " ".join(block).lower()

        if not any(k in text for k in BLOCKED):
            blocks.append("\n".join(block))
    else:
        i += 1

generated = (
    BEGIN_MARKER
    + "\n"
    + "\n\n".join(blocks)
    + "\n"
    + END_MARKER
)

channel = Path(CHANNEL_FILE)
content = channel.read_text(encoding="utf-8")

if BEGIN_MARKER in content and END_MARKER in content:
    content = re.sub(
        re.escape(BEGIN_MARKER)
        + r".*?"
        + re.escape(END_MARKER),
        generated,
        content,
        flags=re.S,
    )
else:
    content += "\n\n" + generated

channel.write_text(content, encoding="utf-8")

print(f"Updated {len(blocks)} soccer events")
