import json
import re
import urllib.request
from pathlib import Path

CHANNEL_FILE = "channel"

BEGIN_MARKER = "# --- BEGIN AUTOGENERATED EVENTS ---"
END_MARKER = "# --- END AUTOGENERATED EVENTS ---"

CDNLIVE_API = (
    "https://api.cdnlivetv.tv/api/v1/events/sports/soccer/"
    "?user=cdnlivetv&plan=free"
)

FWC_ENDPOINTS = [
    ("FIFA World Cup 4K", "https://fifaworldcup.cfd/api/stream?q=4k"),
    ("FIFA World Cup HD", "https://fifaworldcup.cfd/api/stream?q=hd"),
    ("FIFA World Cup ENGLISH", "https://fifaworldcup.cfd/api/stream?q=english"),
]

HEADERS = {
    "User-Agent": "Mozilla/5.0"
}


def normalize_url(url):
    return url.split("?")[0]


def request_text(url, timeout=20):
    req = urllib.request.Request(
        url,
        headers=HEADERS
    )

    return urllib.request.urlopen(
        req,
        timeout=timeout
    ).read().decode("utf-8", "ignore")


def is_valid_m3u(url):
    try:
        text = request_text(url, 15)

        return (
            "#EXTM3U" in text
            and "#EXTINF" in text
        )

    except Exception:
        return False


def fetch_cdnlive():
    events = []

    try:
        data = json.loads(
            request_text(CDNLIVE_API, 30)
        )

        if isinstance(data, dict):
            data = (
                data.get("results")
                or data.get("data")
                or data.get("events")
                or []
            )

        for item in data:

            title = (
                item.get("title")
                or item.get("event")
                or item.get("name")
                or item.get("match")
                or "Football Event"
            )

            stream = (
                item.get("url")
                or item.get("stream")
                or item.get("source")
                or ""
            )

            if not stream:
                continue

            events.append(
                (title, stream)
            )

    except Exception as e:
        print("CDNLiveTV:", e)

    return events


def fetch_fwc():
    events = []

    for title, url in FWC_ENDPOINTS:

        try:

            if is_valid_m3u(url):

                events.append(
                    (title, url)
                )

                print("FWC OK:", title)

            else:

                print("FWC DEAD:", title)

        except Exception as e:

            print("FWC ERROR:", title, e)

    return events


def build_blocks():

    seen = set()
    blocks = []

    sources = []

    sources.extend(
        fetch_cdnlive()
    )

    sources.extend(
        fetch_fwc()
    )

    for title, url in sources:

        key = normalize_url(url)

        if key in seen:
            continue

        seen.add(key)

        block = (
            f'#EXTINF:-1 '
            f'tvg-name="{title}" '
            f'group-title="Group Event",'
            f'{title}\n'
            f'{url}'
        )

        blocks.append(block)

    return blocks


def update_channel():

    channel = Path(CHANNEL_FILE)

    content = channel.read_text(
        encoding="utf-8"
    )

    blocks = build_blocks()

    generated = (
        BEGIN_MARKER
        + "\n"
        + "\n\n".join(blocks)
        + "\n"
        + END_MARKER
    )

    if (
        BEGIN_MARKER in content
        and END_MARKER in content
    ):

        content = re.sub(
            re.escape(BEGIN_MARKER)
            + r".*?"
            + re.escape(END_MARKER),
            generated,
            content,
            flags=re.S,
        )

    else:

        content += (
            "\n\n"
            + generated
        )

    channel.write_text(
        content,
        encoding="utf-8"
    )

    print(
        f"Updated {len(blocks)} events"
    )


if __name__ == "__main__":
    update_channel()
